# Generated by Django 2.1.7 on 2019-02-20 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djeym', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapcontrols',
            name='maptype',
            field=models.CharField(choices=[('yandex#map', 'Scheme'), ('yandex#satellite', 'Satellite'), ('yandex#hybrid', 'Hybrid')], default='yandex#map', max_length=255, verbose_name='Map type'),
        ),
    ]
