"""Generated by Django 6.0.3 on 2026-03-07 20:34."""

from __future__ import annotations

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("djeym", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tilesource",
            name="apikey_is_required",
            field=models.BooleanField(default=False, verbose_name="API Key is required?"),
        ),
    ]
